name: joss paper

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    name: "${{ matrix.pymc-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - pymc-version: "pymc3==3.9.3"
            starry-version: "starry@git+https://github.com/rodluger/starry@master"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - uses: actions/cache@v2
        with:
          path: ~/.theano
          key: ${{ runner.os }}-${{ matrix.pymc-version }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.pymc-version }}-

      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: starry_process
          environment-file: environment.yml

      - name: Set up environment
        shell: bash -l {0}
        run: |
          jupyter nbextension enable --py widgetsnbextension
          sudo apt-get update
          sudo apt-get install ffmpeg

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install -U pip
          python -m pip uninstall -y theano  # so that we know which version we're getting
          python -m pip install ${{ matrix.pymc-version }} ${{ matrix.starry-version }}
          python -m pip install -e ".[app,tests]"
          python -c 'import theano; print(theano.__version__)'

      - name: Figures
        shell: bash -l {0}
        run: |
          cd joss/figures
          ls *.py | xargs -n 1 python

      - name: PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: joss/paper.md

      - uses: actions/upload-artifact@v2
        with:
          path: joss

      - name: Push
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          git checkout --orphan joss-paper
          git rm --cached -rf .
          git add -f joss
          git -c user.name='gh-actions' -c user.email='gh-actions' commit -m "building JOSS paper"
          git push -q -f https://github.com/$GITHUB_REPOSITORY joss-paper
